import random
import struct
import sys
from golden_model import UDPParserGolden, build_udp_frame, build_ethernet_frame


def random_mac():
    return random.randint(0, 0xFFFFFFFFFFFF)


def random_ip():
    return random.randint(0, 0xFFFFFFFF)


def random_port():
    return random.randint(1, 65535)


def generate_test_vectors(num_tests=1000, output_file="test_vectors.txt"):
    """Generate random test vectors and compare against golden model."""
    golden = UDPParserGolden()
    vectors = []
    results = {"passed": 0, "failed": 0, "coverage": set()}

    for _ in range(num_tests):
        enable = random.choice([0, 1])
        dst_port_filter = random.choice([0, random.randint(1, 65535)])
        timestamp = random.randint(0, 0xFFFFFFFFFFFFFFFF)

        golden.configure(dst_port_filter=dst_port_filter, enable=enable, timestamp_value=timestamp)

        frame_type = random.choice(["UDP_match", "UDP_mismatch", "ARP", "IPv4_TCP", "short"])

        if frame_type == "UDP_match":
            dst_port = dst_port_filter if dst_port_filter != 0 else random_port()
            payload = bytes(random.randint(0, 255) for _ in range(random.randint(0, 100)))
            frame = build_udp_frame(random_mac(), random_mac(), random_ip(), random_ip(), random_port(), dst_port, payload)
            results["coverage"].add("UDP_match")

        elif frame_type == "UDP_mismatch":
            dst_port = dst_port_filter + 1 if dst_port_filter < 65535 else 1
            payload = bytes(random.randint(0, 255) for _ in range(random.randint(0, 100)))
            frame = build_udp_frame(random_mac(), random_mac(), random_ip(), random_ip(), random_port(), dst_port, payload)
            results["coverage"].add("UDP_mismatch")

        elif frame_type == "ARP":
            payload = bytes(random.randint(0, 255) for _ in range(random.randint(0, 60)))
            frame = build_ethernet_frame(random_mac(), random_mac(), 0x0806, payload)
            results["coverage"].add("ARP")

        elif frame_type == "IPv4_TCP":
            payload = bytes(random.randint(0, 255) for _ in range(random.randint(0, 60)))
            ipv4_hdr = bytearray(20)
            ipv4_hdr[0] = 0x45
            total_len = 20 + len(payload)
            struct.pack_into('>H', ipv4_hdr, 2, total_len)
            ipv4_hdr[9] = 6
            frame = build_ethernet_frame(random_mac(), random_mac(), 0x0800, bytes(ipv4_hdr) + payload)
            results["coverage"].add("IPv4_TCP")

        else:
            frame = bytes(random.randint(0, 255) for _ in range(random.randint(1, 20)))
            results["coverage"].add("short")

        output, dropped, ts_used = golden.process_frame(frame)

        if dropped:
            expected_output = "NULL"
            expected_drop = 1
        else:
            expected_output = frame.hex() if output is None else output.hex()
            expected_drop = 0

        vectors.append({
            "frame": frame.hex(),
            "dst_port_filter": dst_port_filter,
            "enable": enable,
            "expected_output": expected_output,
            "expected_drop": expected_drop,
            "timestamp": timestamp if not dropped and enable and dst_port_filter != 0 else 0
        })

        results["passed"] += 1

    with open(output_file, "w") as f:
        f.write("# Test vectors generated by random_test.py\n")
        f.write("# Total vectors: %d\n" % len(vectors))
        f.write("# Format: frame_hex filter enable expected_output_hex expected_drop timestamp\n")
        f.write("# NULL = dropped frame\n\n")

        for v in vectors:
            f.write("%s %d %d %s %d %d\n" % (v["frame"], v["dst_port_filter"], v["enable"], v["expected_output"], v["expected_drop"], v["timestamp"]))

    print("Generated %d test vectors -> %s" % (len(vectors), output_file))
    print("Passed: %d, Failed: %d" % (results["passed"], results["failed"]))
    print("Coverage: %s" % sorted(results["coverage"]))

    return vectors


if __name__ == "__main__":
    num = 1000
    if len(sys.argv) > 1:
        num = int(sys.argv[1])
    generate_test_vectors(num)